{{- $name := include "s3app.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-envvar
  labels:
    app: {{ $name }}
    chart: {{ include "s3app.chart" . }}
    release: {{ .Release.Name }}
{{- with .Values.k8s.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  S3APP_THREADS: "{{ .Values.app.server.threadsPerReplica }}"
  S3APP_LISTENER_IP: 0.0.0.0
  S3APP_LISTENER_PORT: '8080'
  S3APP_CONF_FILE: /usr/src/app/webapp/.env
