{{- if .Values.ingress.enabled }}
{{- $name := include "s3app.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ include "s3app.chart" . }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.hostnames }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
{{- end }}
  rules:
{{- range .Values.hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $.Values.listenerPort }}
{{- end }}
{{- end }}