apiVersion: v2
version: 1.2.7
appVersion: 1.2.7
name: s3app
description: |
  S3App simplifies the access to a S3Buckets with a provider independent web based frontend which allows
  the visualizing and the management of the co                                                                                                       ntent of S3 buckets.
home: https://www.yotron.de
icon: https://www.yotron.de/img/logo-yotron.png
sources:
  - https://github.com/yotron/s3app/
dependencies:
  - name: postgresql
    version: "11.9.5"
    repository: https://charts.bitnami.com/bitnami
    condition: app.database.pgInternal
  - name: k8s-secrets
    version: 1.0.0
    repository: http://helm.yotron.de
    alias: certs
    condition: certs
maintainers:
- email: joern.kleinbub@yotron.de
  name: joern.kleinbub
  url: https://www.yotron.de
